apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: order-service
  namespace: services
spec:
  host: order-service.services.svc.cluster.local
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
