apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: payment-service
  namespace: services
spec:
  hosts:
    - payment-service.services.svc.cluster.local
  http:
    - name: default
      route:
        - destination:
            host: payment-service.services.svc.cluster.local
            subset: stable
