{{- if eq (.Values.version | default "stable") "stable" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceName }}
    managed-by: helm
{{- end }}
